#/bin/sh

set -o errexit -o nounset

if [ "$TRAVIS_BRANCH" != "master" ]
then
  echo "This commit was made against the $TRAVIS_BRANCH and not the master! Do not deploy!"
  exit 0
fi

# User info
git config user.name "Admin"
git config user.email "patternfly@redhat.com"

# Add upstream authentication token
git remote add upstream https://$AUTH_TOKEN@github.com/patternfly/angular-patternfly.git

# Commit generated files
git add dist --force
git commit -m "Added files generated by Travis build"

# Push to remote branch
git push upstream $TRAVIS_BRANCH:releases --force -v

exit $?
